
[build]
  
  command = "npm ci && npm run build"
  publish = "public"


[[redirects]]
  from   = "/:folder/*"
  to     = "/:folder/index.html"
  status = 200


[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
